server:
  port: 8080

# database settings
spring:
  datasource:
    url: jdbc:postgresql://[DB_HOST]:5432/[Database]
    username: [DB_USER_NAME]
    password: [PASSWORD]
    driver-class-name: org.postgresql.Driver